### ISSUE TITLE
Microsoft Edge Web Browser does not shows the sections title

### ISSUE THREAD

**Issue by tiagochst** [BioinformaticsFMRP/TCGAbiolinksGUI#12]
![error_menu](https://cloud.githubusercontent.com/assets/145529/22758596/7e2ae438-ee36-11e6-9b47-fd29b981b9d6.PNG)

**Comment by DarioS** [comment]
I also get blank Genes info.

![genesinfo](https://cloud.githubusercontent.com/assets/631218/25778605/3d563098-3346-11e7-9584-8b459910c0b6.png)

**Comment by tiagochst** [comment]
@DarioS I fixed it. After the DEA isc ompleted it will show the results
<img width="2249" alt="screen shot 2017-06-08 at 2 58 35 pm" src="https://user-images.githubusercontent.com/145529/26952602-110730cc-4c5b-11e7-9a9c-e50f4f8d35d9.png">
