### ISSUE TITLE
Search Results Summary Lacks Number of Samples

### ISSUE THREAD

**Issue by DarioS** [BioinformaticsFMRP/TCGAbiolinksGUI#14]
After doing a molecular data search and applying a filter, it's not clear how many samples meet the rules. Initially, the Summary pie charts are shown, which only display percentages. It's not until expanding the Results panel that the number of samples can be seen in the bottom left corner, below the table. This information should be easier to find.

**Comment by labrazil** [comment]
Fully agree. Thank you for the suggestion. This should be an easy fix.

**Comment by tiagochst** [comment]
The number was available if you hover the pie chart like the screenshot below.
<img width="730" alt="captura de tela 2017-05-10 as 00 18 19" src="https://cloud.githubusercontent.com/assets/145529/25899374/86a94ce2-3587-11e7-8629-6f6fe07764b9.png">

But I agree it should be more visible. I'm changing % to values.
<img width="705" alt="captura de tela 2017-05-10 as 13 51 20" src="https://cloud.githubusercontent.com/assets/145529/25899488/faa36cd6-3587-11e7-8106-d71b63170bd3.png">

**Comment by labrazil** [comment]
Tiago, I don't agree.  Keep the %, and we just need to make a note on that
page to inform the user that they can hover over the pie chart to get
absolute numbers.  Percentages are useful in this regards.


Houtan

--
\hn
Ph: +1-310.570.2362
Not sent from my pıoɹpuɐ device.

**Comment by labrazil** [comment]
Or if possible, a table underneath the pie charts, while still keeping the
% in the pie, would suffice this Users suggestion.


Houtan

--
\hn
Ph: +1-310.570.2362
Not sent from my pıoɹpuɐ device.

**Comment by tiagochst** [comment]
The UI is already quite heavy, I prefere not to add new elements that are not extremely important. 
I will keep the % and add a bar chart with the number of samples.

**Comment by labrazil** [comment]
Great point. Thanks Tiago.


Houtan

--
\hn
Ph: +1-310.570.2362
Not sent from my pıoɹpuɐ device.

**Comment by tiagochst** [comment]
This is the last plot
<img width="714" alt="screen shot 2017-05-11 at 9 41 40 am" src="https://cloud.githubusercontent.com/assets/145529/25961147/1e530eec-362e-11e7-93b1-d2e65dc7f503.png">
