### ISSUE TITLE
Gene Symbols Are Missing From DEA Results

### ISSUE THREAD

**Issue by DarioS** [BioinformaticsFMRP/TCGAbiolinksGUI#15]
It will annoy the biologists.

```
mRNA            logFC     	FDR             male            female          Delta           status                  Gene_symbol
ENSG00000129824	-9.601111955	5.80E-30	114.5312859	0.025120624	1099.627698	Downregulated in female	ENSG00000129824
```

In this test case, shouldn't `Gene_symbol` be RPS4Y1 rather than its ENSEMBL ID? Also, what does the Delta column contain? It's not documented anywhere I can see.

**Comment by labrazil** [comment]
Hi Dario, great suggestion and I agree the ENSG would be an inconvenience for biologists. We will work out a solution, maybe a link /or add a new column to extract the canonical gene ID.

**Comment by tiagochst** [comment]
@torongs82  This is also a TCGAbiolinks problem. Could you please add the delta explanation in the TCGAbiolinks, I'll add later in the documentation of the GUI. I'll add a function to check if ENSG is used the add gene symbol to the results.

**Comment by torongs82** [comment]
hi @DarioS, thank you for your interest in TCGAbiolinksGUI. Yes indeed I have to add more details about delta in TCGAbiolinks as well. Let say that for each gene you can have mean expression of Tumor samples (meanT) and mean expression of Normal samples (meanN) --> Delta basically is |logFC| * |meanT - meanN|

**Comment by tiagochst** [comment]
For the last version of TCGAbiolinks and TCGAbiolinksGUI the gene symbols were added.

<img width="1100" alt="captura de tela 2017-05-11 as 17 09 41" src="https://cloud.githubusercontent.com/assets/145529/25976929/bf5b29e4-366c-11e7-89fa-211453a304f6.png">

**Comment by DarioS** [comment]
The mRNA and ensembl_gene_id columns seem redundant.
