### ISSUE TITLE
Summary pie charts don't show up in Safari or Google Chrome Browsers

### ISSUE THREAD

**Issue by AmyOlex** [BioinformaticsFMRP/TCGAbiolinksGUI#16]
I've tried 3 browsers and found that when you hit "Visualize Data" button the pie charts don't show up in Safari or Google Chrome. They do show up fine in FireFox, so I think this is a browser compatibility issue. I have Safari 9.1.3, Chrome v58, and FireFox v29.  I'm using the TCGABiolinksGUI implementation found at "https://tcgabiolinksgui.shinyapps.io/tcgabiolinks/".

**Comment by AmyOlex** [comment]
Nevermind, it is working in Chrome now.  Still not in Safari though.

**Comment by tiagochst** [comment]
Thank you for reporting, I checked and it is really not showing in safari.

**Comment by tiagochst** [comment]
So this is a googlevis problem. The function `gvisMerge` is not rendering for safari and even in the Rstudio viewer. You would need to either report the problem, or change the package.

**Comment by tiagochst** [comment]
And the last version of the GUI is found in: http://tcgabiolinks.fmrp.usp.br:3838/ or https://tcgabiolinksgui.shinyapps.io/demo/. That link was old.
