### ISSUE TITLE
"Error while preparing files" when attempting to download GDC Molecular Data as a Summarized Experiment

### ISSUE THREAD

**Issue by maxxu05** [BioinformaticsFMRP/TCGAbiolinksGUI#17]
This is my first time doing any sort of bioinformatics data analysis and working with kitematic. When I attempt to "Download & Prepare" the GDC Molecular Data as a "SummarizedExperiment", there is an error that states "Error while preparing the files." There are no other error messages besides that. I also made sure to install the SummarizedExperiment package here: http://bioconductor.org/packages/release/bioc/html/SummarizedExperiment.html.

The data I am attempting to download is Harmonized database (hg38) > TCGA-SKCM >Transcriptome_Profiling > Gene_Expression_Quantification > HTSeq - Counts

**Comment by tiagochst** [comment]
I made some fixes this week, but I did not sent to the docker image yet. I'll do it and post here.

**Comment by maxxu05** [comment]
thanks!

**Comment by maxxu05** [comment]
When do you think that you will have sent it to the docker image by? Thanks

**Comment by tiagochst** [comment]
Probably in some hours, I'm building it, then I need to test

**Comment by tiagochst** [comment]
I tested with  kitematic it is working
![Uploading Screen Shot 2017-06-14 at 5.03.36 PM.png…]()

**Comment by tiagochst** [comment]
Also the old version wasn't

**Comment by maxxu05** [comment]
I tested it again and I am still unable to download the data as a "SummarizedExperiment" It is still giving me the same exact error of "Error while preparing files"
![image](https://user-images.githubusercontent.com/29440154/27162610-4107189c-5150-11e7-894f-b6ee971de8e3.png)
