### ISSUE TITLE
Still an "Error while preparing files" when downloading as Summarized Experiment

### ISSUE THREAD

**Issue by maxxu05** [BioinformaticsFMRP/TCGAbiolinksGUI#18]
My previous issue was not fully resolved before being marked as resolved, so I am reposting the issue. I am still unable to download the GDC data as a summarized experiment, even after the new patch. Here is a picture of it failing for reference. 
![image](https://user-images.githubusercontent.com/29440154/27163194-cf41a534-5153-11e7-8200-0b7fda477683.png)

Thank you for your help!

**Comment by tiagochst** [comment]
I was not able to replicate the problem. I uploaded a new version in docker, it should appear in the error message the problem. Also, I'm updating the progress bar in the prepare function.

<img width="249" alt="screen shot 2017-06-15 at 11 40 49 am" src="https://user-images.githubusercontent.com/145529/27196782-b6c38122-51c0-11e7-89ef-822e7dcab90e.png">

Please, could you delete the image, download again and test.

**Comment by maxxu05** [comment]
After deleting the image and redownloading, it is now working again!
