### ISSUE TITLE
There are random columns within the dataframe that contain row labels. In volumes, data is not saving locally.

### ISSUE THREAD

**Issue by maxxu05** [BioinformaticsFMRP/TCGAbiolinksGUI#19]
I downloaded a dataframe to work with but I am now unable to convert it into a numeric matrix due to the columns with row labels within them every 21 columns. Before your recent patch, I was not having this problem, so it seems like this patch introduced this issue. Attached is a picture for your reference,

Additionally, is it necessary for me to delete the entire image in order to update the GUI? When I deleted the image previously, I lost all my files that I had saved onto the docker. Even though I set up the volumes to a local folder, it was still deleted. Even now as I work on the new GUI, I am saving stuff in the docker volume, but it is not showing up in the local folder.

Thank you so much for your help. I really appreciate it!

![image](https://user-images.githubusercontent.com/29440154/27231951-5862a596-5282-11e7-9263-02882bac9eab.png)

**Comment by tiagochst** [comment]
Sorry, I know where the mistake is, that was not supposed to happen. I'll need to change it back to the old way.

**Comment by maxxu05** [comment]
thank you! could you also address the issue of the data not saving in the local folders specified by volumes? I have been saving various data inside the container but it is not also saving in my local folder.

**Comment by maxxu05** [comment]
photos for reference 
![image](https://user-images.githubusercontent.com/29440154/27237825-8bd9ba52-5298-11e7-96e3-023dcc0fe46b.png)

**Comment by tiagochst** [comment]
The only way to update would be to open a terminal and type `sudo docker pull tiagochst/tcgabiolinksgui`, I was not able to find it in kitematic (in that case you will need to remove and download again). Updating using the terminal should not erase the folder.

I updated to add a new volume.  Now you will be able to get the files.
<img width="1454" alt="screen shot 2017-06-16 at 10 48 48 am" src="https://user-images.githubusercontent.com/145529/27238383-7f628310-5281-11e7-8733-57a0b0702d3c.png">

**Comment by maxxu05** [comment]
thank you! I think those problems are now fixed
