### ISSUE TITLE
Constant disconnects with GUI with it being  very slow and certain features not loading

### ISSUE THREAD

**Issue by maxxu05** [BioinformaticsFMRP/TCGAbiolinksGUI#20]
After a while with it running normally, the GUI will begin disconnecting very frequently and I am unable to select various data types while attempting to download GDC data. After a computer restart usually it starts working normally for a while until breaking again. Is this an issue on my end or how the GUI is set up?

update: I downloaded TCGAbiolinksGUI on another computer, and it is unable to load the GUI at all before "disconnected from server." The shiny server home page loads fairly quickly with no problem, but when I type in "/tcgabiolinksgui" then the gui won't load

**Comment by maxxu05** [comment]
picture for reference (I am unable to load the GUI because if the server disconnect which happens almost immediately: 
![image](https://user-images.githubusercontent.com/29440154/27386293-561c39d4-5663-11e7-97e0-d6ebeadd5ebc.png)

**Comment by jpburckert** [comment]
Was there a solution to this?
