### ISSUE TITLE
Unable to download molecular data with "clinical data" with category filter"

### ISSUE THREAD

**Issue by maxxu05** [BioinformaticsFMRP/TCGAbiolinksGUI#21]
![image](https://user-images.githubusercontent.com/29440154/27551212-87ab5514-5a70-11e7-9292-ad94cd9e8602.png)

Error while preparing the files
Error in if (data.type == "Clinical data") {: missing value where TRUE/FALSE needed

**Comment by tiagochst** [comment]
It is a bug, I need to remove that category from there.
Clinical data should be download in GDC DATA menu -> Clinical data sub-menu

<img width="187" alt="captura de tela 2017-06-26 as 17 25 54" src="https://user-images.githubusercontent.com/145529/27565671-8c4359ea-5a94-11e7-8784-4d8fe889869d.png">
d
