### ISSUE TITLE
All results of "subtype data search" are the same, no matter what tumor is selected

### ISSUE THREAD

**Issue by maxxu05** [BioinformaticsFMRP/TCGAbiolinksGUI#23]
![image](https://user-images.githubusercontent.com/29440154/27706232-cf0b1622-5cde-11e7-9a57-efadba2ff0f1.png)

![image](https://user-images.githubusercontent.com/29440154/27706243-dafb88fe-5cde-11e7-9297-9bf0557bb72d.png)

![image](https://user-images.githubusercontent.com/29440154/27706246-e49e4388-5cde-11e7-81cb-35479ca32915.png)

**Comment by maxxu05** [comment]
you closed it but after deleting and redownloading the image, I still have the same error. No matter what tumor I choose, I will have the same results table

**Comment by tiagochst** [comment]
Hi,
I'm sorry but I didn't update the docker image yet. Only the package.

Em sex, 7 de jul de 2017 13:25, maxxu05 <notifications@github.com> escreveu:

**Comment by maxxu05** [comment]
Ah I see, thank you. When do you think that update will be in by?
