### ISSUE TITLE
"Error in [: subscript out of bounds" when using DEA

### ISSUE THREAD

**Issue by b614103080** [BioinformaticsFMRP/TCGAbiolinksGUI#27]
Hi, I followed the steps in this document(https://drive.google.com/file/d/0B0-8N2fjttG-TVVOcTNFRlh3YXM/view).
But after I added a new column to sample data matrix(csv) and saved a new summarized experiment, I cannot conduct the DEA analysis with this file.

It shows "disconnect from server"
R studio shows "Error in [: subscript out of bounds".

If I don't manage summarized experiment and just conduct the DEA with downloaded rda file, it works.

I am using docker image on Mac, change csv file with Numbers and Libre office. (But even if I use the original csv file and save the summarized experiment, it cannot work)

Thanks for help.

**Comment by tiagochst** [comment]
Hello, there was a bug in the data creation. Thank you for posting the problem.
I solved it, I'll update the docker image.

**Comment by b614103080** [comment]
Really thanks for your work! This problem has troubled me for a long time.
