### ISSUE TITLE
how to download expression data file from TCGAbiolinks GUI 

### ISSUE THREAD

**Issue by varun171** [BioinformaticsFMRP/TCGAbiolinksGUI#28]
How to download CSV files from TCGAbiolinks GUI to local computer

**Comment by tiagochst** [comment]
The tables can be exported/downloaded using the buttons (csv, pdf etc). Due to some updates in the libraries, I had to update the code to make it work again.
<img width="1260" alt="screen shot 2017-08-29 at 11 25 15 am" src="https://user-images.githubusercontent.com/145529/29837439-f862be14-8cac-11e7-9dd4-57bf7a1ddf79.png">

The same is able for the DEA results
<img width="1255" alt="screen shot 2017-08-29 at 11 37 12 am" src="https://user-images.githubusercontent.com/145529/29837919-730174c0-8cae-11e7-9f9e-7525060f4469.png">

Do you have, any specific file?

**Comment by tiagochst** [comment]
You will need to install from github, I updated the devel in Bioconductor, but not the release.
`devtools::install_bioc("BioinformaticsFMRP/TCGAbiolinksGUI")`

**Comment by varun171** [comment]
Thank you so much.

Varun

**Comment by varun171** [comment]
it is not working. It is asking for package DT.

**Comment by tiagochst** [comment]
Please, could you install it with `install.packages("DT")`. I just changed to install it by default.

**Comment by varun171** [comment]
I did it. It is working now. Thanks

**Comment by varun171** [comment]
It is not saving complete file.  when I click the full list and save. it
just got disconnected. Can you suggest R command to convert .rda object in
CSV files? I have already downloaded .rda files. I can convert offline.  It
will be a great help.

Varun

**Comment by manalirupji** [comment]
I am trying to download raw counts RNA seq experiment for a subset of 45 samples. Even though I enter the barcodes in the section, I see all 1200+ samples in the middle results section. I also tried the example ACC dataset in the tutorial and see the same issue.

**Comment by tiagochst** [comment]
I'll check. Please, could you send me the list of barcodes?

**Comment by varun171** [comment]
Can we download complete excel file?

**Comment by manalirupji** [comment]
Sure, 
TCGA-A2-A0CU
TCGA-EW-A1P8
TCGA-A2-A0T2
TCGA-E2-A1LK
TCGA-BH-A8FY
TCGA-AR-A5QQ
TCGA-AR-A1AR
TCGA-BH-A1EY
TCGA-A2-A04P
TCGA-B6-A409
TCGA-A2-A0YT
TCGA-BH-A1F8
TCGA-A2-A0CM
TCGA-BH-A1F0
TCGA-AC-A2FM
TCGA-B6-A0X4
TCGA-E2-A1LE
TCGA-A2-A3XU
TCGA-A2-A0CR
TCGA-AO-A129
TCGA-B6-A0RV
TCGA-B6-A0RT
TCGA-A2-A0EN
TCGA-Z7-A8R5
TCGA-AO-A128
TCGA-E2-A1LH
TCGA-AO-A126
TCGA-AO-A125
TCGA-3C-AAAU
TCGA-B6-A2IU
TCGA-A2-A04N
TCGA-B6-A1KN
TCGA-B6-A0IA
TCGA-B6-A0X1
TCGA-A2-A0EM
TCGA-A2-A0ST
TCGA-AO-A03P
TCGA-AR-A24H
TCGA-A2-A0EP
TCGA-A2-A0CO
TCGA-GM-A2DA
TCGA-B6-A1KF
TCGA-GM-A3NW
TCGA-E2-A1LI
TCGA-A2-A0CK

**Comment by tiagochst** [comment]
The button is only exporting what is showing, you would have to select to see all rows, but for that would take sometime to load. I'll see what I can do to make it better.

If you have the rda object you can get the raw counts with:
```
library(SummarizedExperiment);
obj <- get(load("TCGA-ACC_Transcriptome_Profiling_Gene_Expression_Quantification_hg38.rda"))
readr::write_csv(as.data.frame(assay(obj)), "rawcounts.csv")
```

The barcode filter is working for me I only get 49 samples (probably there are recurrent or duplicated patients samples):
<img width="1436" alt="screen shot 2017-08-30 at 12 43 48 pm" src="https://user-images.githubusercontent.com/145529/29891808-44969e66-8d81-11e7-8703-6d049c20105d.png">
<img width="1433" alt="screen shot 2017-08-30 at 12 42 42 pm" src="https://user-images.githubusercontent.com/145529/29891807-448dbc10-8d81-11e7-8ce8-8422db331508.png">
<img width="1261" alt="screen shot 2017-08-30 at 12 53 04 pm" src="https://user-images.githubusercontent.com/145529/29892105-33233328-8d82-11e7-86bb-595401ba39b2.png">

**Comment by varun171** [comment]
Thanks. I really appreciate.

Varun

**Comment by manalirupji** [comment]
Thanks so much for the insight! Also, could you please guide how to save the .rda object on my local machine using the GUI interface?

**Comment by varun171** [comment]
Hello Mr. Silva, Is there any way I can get gene name and entrez ID also in
CSV file with this script. I m getting only raw counts with this script.

Thanks

Varun

library(SummarizedExperiment);

obj <- get(load("TCGA-ACC_Transcriptome_Profiling_Gene_Expression_Quantification_hg38.rda"))
readr::write_csv(as.data.frame(assay(obj)), "rawcounts.csv")

**Comment by tiagochst** [comment]
@manalirupji I just added a button in the configuration menu to do it.
https://youtu.be/Ib2SAR3tZUM

**Comment by varun171** [comment]
Thanks. It will be very helpful.

Varun
