### ISSUE TITLE
R is outdated, still 3.4.1

### ISSUE THREAD

**Issue by sky1ove** [BioinformaticsFMRP/TCGAbiolinksGUI#35]
I've already installed the latest R, but when running TCGAbiolinksGUI on Kitematic, it still showed 3.4.1.  I've tried to update R on the interface, but other packages such as installr or updateR are incompatible with R 3.4.1.  

I tried to upgrade R because I thought that might be the reason I couldn't get my summerized Experiment

**Comment by tiagochst** [comment]
I'll try to update the R version in the docker image.
For the summerized Experiment problem, could you give more details which data you are trying to download and prepare? Some data like protein, and miRNA are not prepared as summerized Experiment objects.

**Comment by tiagochst** [comment]
The docker images was updates. 

<img width="451" alt="screen shot 2018-01-07 at 3 28 18 pm" src="https://user-images.githubusercontent.com/145529/34651983-6c1e4ade-f3bf-11e7-86de-4aad2d3849a3.png">

**Comment by tiagochst** [comment]
The image is here: https://hub.docker.com/r/tiagochst/tcgabiolinksgui/
