### ISSUE TITLE
The package is not available on Bioconductor

### ISSUE THREAD

**Issue by armish** [BioinformaticsFMRP/TCGAbiolinksGUI#7]
See the broken link, [https://bioconductor.org/packages/TCGAbiolinksGUI/](https://bioconductor.org/packages/TCGAbiolinksGUI/), and also the following failed attempt to install the package within R:

```
> source("https://bioconductor.org/biocLite.R")
> biocLite("TCGAbiolinksGUI")
...
package ‘TCGAbiolinksGUI’ is not available (for R version 3.3.2) 
```

**Comment by labrazil** [comment]
Thank you. Yes we are aware. It's currently in the process of being
incorporated into bioconductor. Please install the GUI via our github
repository. Thanks.

**Comment by tiagochst** [comment]
We sent the package almost two months ago, but the last communication we received was beginning December. You can follow the status [here](https://github.com/Bioconductor/Contributions/issues/182).

**Comment by labrazil** [comment]
The package is now on bioconductor. It can be found within the devel version. Upon the next bioconductor release, TCGAbiolinksGUI will be available. 

https://bioconductor.org/packages/TCGAbiolinksGUI/

**Comment by armish** [comment]
That's great news! Thanks for being proactive about this. Closing the issue as you already addressed this.
