### ISSUE TITLE
The demo page linked from the README file doesn't work

### ISSUE THREAD

**Issue by armish** [BioinformaticsFMRP/TCGAbiolinksGUI#8]
See: https://tcgabiolinksgui.shinyapps.io/TCGAbiolinksGUI/

![broken demo](https://cl.ly/1t082C3o1c2Z/Image%202017-01-20%20at%204.30.26%20PM.png)

**Comment by labrazil** [comment]
Thank you for alerting us. We were fortunate to have an opportunity to host our package on shiny, however their site is not always dependable. We are looking at alternatives sites, but these will all become temporary once bioconductor incorporates our package,which we assume will happen shortly. 
Thanks.

**Comment by tiagochst** [comment]
The one that is running the last version is
[https://tcgabiolinksgui.shinyapps.io/tcgabiolinks/](https://tcgabiolinksgui.shinyapps.io/tcgabiolinks/)

I need to fix the name. I'll do it soon.
